### PR TITLE
Gd patches

### PR DESCRIPTION
**Pull request by janpriessnitz**

### CODE REVIEW

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci-dev.intgdc.com/job/zuul-tox-zuul/8/ : FAILURE in 1m 06s

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci-dev.intgdc.com/job/zuul-tox-zuul/9/ : FAILURE in 1m 06s

**Pull request merged**
